### ISSUE TITLE
Support for STL as one of the models?

### ISSUE THREAD

**Issue by paulhendricks** [ellisp/forecastHybrid#10]
This of course uses STL to de-seasonalize, model the trend-cycle-remainder using a non-seasonal forecasting method (typically ARIMA or ETS), and then re-seasonalizes using the last annum of seasonal components.

In my experience, this has worked as well an sometimes better than ARIMA or ETS. Any thoughts of including this as well?

**Comment by dashaub** [comment]
Good addition.

**Comment by dashaub** [comment]
closed in commit ca79905f9bdf29097ba6543d466d68746863e980
