### ISSUE TITLE
do we want to check on a.args, s.args, etc separately; or just leave it up to auto.arima() etc to cope?

### ISSUE THREAD

**Issue by ellisp** [ellisp/forecastHybrid#13]
Just putting this as an issue while cleaning the comment out of the code

**Comment by dashaub** [comment]
I was thinking we'd pass the arguments on to the auto.arima/ets/nnetar/stlm/tbats functions as-is. Those functions already do very robust error-handling, so any invalid arguments in those lists will give the user a very descriptive error anyway. Duplicating that validation wouldn't seem advisable unless there is a compelling reason.

**Comment by ellisp** [comment]
I agree.
