### ISSUE TITLE
Additional models

### ISSUE THREAD

**Issue by dashaub** [ellisp/forecastHybrid#14]
We should consider handling additional models. If we implement issue #11 this will need to be considered.
Furthermore, once this package is stable I'd like to work on and include arar/ararma models (see https://github.com/robjhyndman/forecast/issues/8)

`bats()` models might be an addition. Since they are quite similar to `tbats()` it may not be worth inclusion, but they can provide better fits with default settings in some causes (e.g. compare `bats(taylor)` to `tbats(taylor)`).

**Comment by ellisp** [comment]
Cross reference #50 and #51 for two other possibilities.
