### ISSUE TITLE
ggplot graphics

### ISSUE THREAD

**Issue by dashaub** [ellisp/forecastHybrid#21]
The basic plots were closed in #1 , but we should still consider adding `ggplot2` support.

**Comment by ellisp** [comment]
This has come automagically with forecast 7 but I notice the multi-line titles don't work.  I'll try to have a look.

**Comment by dashaub** [comment]
@ellisp Cool, I saw this on the "forecast" development plan a while back and figured it was definitely worth waiting and inheriting the functionality from them. It should be fairly easy to incorporate, probably a matter of adding a `ggplot = TRUE` argument to our `plot.hybridModel()` function and then adding some additional logic to use `autoplot`, etc when appropriate.

**Comment by dashaub** [comment]
@ellisp Partially implemented here: c47b0e3e8aced8a55269188474942b9174b69cf1
We still need to handle when `type = "fit"`

**Comment by dashaub** [comment]
The easiest way to finish this off could be to create a dataframe of fitted values from each component model and `reshape2::melt()` it as done [here](https://stackoverflow.com/questions/3777174/plotting-two-variables-as-lines-using-ggplot2-on-the-same-graph).
The x asis label can be preserved using `as.Date(time(inputSeries))` as done [here](https://stackoverflow.com/questions/26327991/directly-plotting-ts-object-with-ggplot2).
