### ISSUE TITLE
cross validation

### ISSUE THREAD

**Issue by dashaub** [ellisp/forecastHybrid#36]
This should be pretty easy to implement like these sources:
http://robjhyndman.com/hyndsight/tscvexample/
http://www.r-bloggers.com/functional-and-parallel-time-series-cross-validation/

The biggest thought will need to go into the function header and how to handle parallelization. If we're not careful parallelization could be a complete disaster given all the levels we can parallize (i.e. within models, between models, for cross validation, and for choice of `aenst` models).

**Comment by tyokota** [comment]
Those examples require parameters for various models be pre-filled prior to running the loop. How would this be handled with forecastHybrid? More so curious as I also recently came across these posts. Also seems to lose the ability to leverage automated forecast like auto.arima()?

**Comment by dashaub** [comment]
I'm thinking the cross validation would be performed at the stage of deciding what weights to use when combing the component models, not for deciding the parameters of the component models; that is in fact the purpose of `auto.arima` and the other function in the "forecast" package. There are lots of ways to do this. I envision this being accomplished in a new function, `cv.ts(data, FUN = function(x, ...), FCFUN = function(x, h, ...), rolling = TRUE, window = 10, horizon = 5)`. It probably won't look exactly like that, but thinking about how to structure this function is the biggest difficult. As a main point it needs to accept the data, the function used for selecting a model, and the function used to build the forecast from the model. Additional arguments will  control the type of CV to perform. Then if the user selects `weights = "cv.errors"` in `hybridModel()`, we simply use the CV errors created by `cv.ts()` for the weights.

This is going to be a really computationally expensive, and it is a task that can be parallelized easily, but we need to think carefully about at what level we perform the parallelism. That said, this is a feature I'd definitely like to implement this summer and at which point I'd consider the "forecastHybrid" package complete with its core functionality (obviously we'll continue development and add new features when possible after that).

**Comment by dashaub** [comment]
Getting this to work with a `xreg` argument will be tricky. We might start by now supporting that for now.
