### ISSUE TITLE
parallelize cvts

### ISSUE THREAD

**Issue by ellisp** [ellisp/forecastHybrid#53]
As a first step towards #5, allow cvts to work in parallel.

**Comment by ganesh-krishnan** [comment]
@dashaub What's your preferred approach for implementing this? I'm thinking foreach. Any objections?

**Comment by dashaub** [comment]
I'd use "foreach" too and register a parallel backend with "doParallel" since it supports UNIX and Windows systems and is a few lines of code. If you have another preferred way to register a parallel backend I'm open to it.

**Comment by dashaub** [comment]
Added here: 9d687ec14e9ea385a33088a174065f1a07395e56
