### ISSUE TITLE
I am trying to use a library(forecasthybrid) from r.net

### ISSUE THREAD

**Issue by savvaskef** [ellisp/forecastHybrid#59]
i am having problems with forecast that doesn't seem to accept level argument (even if i use two CIs)plus i cannot find how to use install.packages(pathtotar,dependencies=TRUE,repos=NULL, type=\"source\")"

do you know of these problems?do you know of a direct solution or a way to work around the problem?

**Comment by dashaub** [comment]
1. Can you provide an exact reproducible example with the data and function call to `forecastHybrid()`?

2. Sounds like you're looking for something like [this](https://stackoverflow.com/questions/1474081/how-do-i-install-an-r-package-from-source).

**Comment by savvaskef** [comment]
ooops! unexpected error.. The error was caused not by the level but because all data where the same (100% CI) and such as the project could not comprehend the forecast function .

as for the other problem i am opening a new issue since this stupid mistake of mine will obviously be removed from knowledge base. :
