### ISSUE TITLE
cvts vignette

### ISSUE THREAD

**Issue by dashaub** [ellisp/forecastHybrid#66]
Add a `cvts()` vignette. This might have to wait while we work out the new API to handle xreg.

**Comment by dashaub** [comment]
added 70d72629755da8ab8b6843fd66b9deea8d3c3f44

**Comment by russellcameronthomas** [comment]
In the last example of this vignette, you wrote (emphasis added):

> As a final example, suppose we _foolish_ want to implement our own version of `naive()` for performing cross validation.

I think I understand what you are trying to convey, but it is poorly worded for most readers, especially anyone who doesn't read English as a first language.  Nobody will "foolishly want to implement their own version of `naive()`".

May I suggest this instead:

> As a final example, I want to illustrate how you can write a custom model function (for the `FUN` parameter) and a custom forecast function (for the `FCFUN`parameter) to cross validate nearly any model.  For illustration purposes only, I will implement a `naive()` model, where the forecast is simply a repetition of the last actual value in the time series.
