### ISSUE TITLE
stlm not back transforming when lambda != 1

### ISSUE THREAD

**Issue by ellisp** [ellisp/forecastHybrid#67]
Just noticed this:

```R
model1 <- hybridModel(AirPassengers, lambda = 0)
plot(model1, main = "something wrong with stlm when lambda != 1")

model2 <- hybridModel(AirPassengers)
plot(model2, main = "problem doesn't happen when lambda == 1")
```

![image](https://cloud.githubusercontent.com/assets/5740570/22037446/0a193198-dd5c-11e6-9327-644070692429.png)

![image](https://cloud.githubusercontent.com/assets/5740570/22037452/0ebeda86-dd5c-11e6-9ecc-cba7693ac9b2.png)

I'm happy to sort it in the next few days unless @dashaub wants to take it on.

**Comment by dashaub** [comment]
@ellisp pretty swamped now, so if you can sort it out that'd be great. I took a quick look at the code in `hybridModel()` and didn't immediately see anything wrong. I'd check to see if it reproduces in `stlm()`.

**Comment by dashaub** [comment]
opened an issue [here](https://github.com/robjhyndman/forecast/issues/482).

**Comment by dashaub** [comment]
It appears to work fine on the Github "forecast" version.
