### ISSUE TITLE
forecastHybrid CRAN update needed

### ISSUE THREAD

**Issue by robjhyndman** [ellisp/forecastHybrid#72]
The forecast package will be updated on CRAN soon. The new version is causing forecastHybrid to error on a CRAN check:

> `Failure: Testing is.hybridModel(), fitted.hybridModel(), residuals.hybridModel(), and accuracy.hybridModel() (@test-hybridModel.R#73)`

The issue is that we have moved zoo from a Dependency to an Import in the forecast package. I think the solution is for you to import `zoo::as.Date.ts()`.

**Comment by dashaub** [comment]
Appears to be fixed with the import, thanks for the heads up. I hope to push to CRAN soonish.
