### ISSUE TITLE
libcudart version

### ISSUE THREAD

**Issue by beew** [ellisp/forecastHybrid#85]
Tried to install forecastHybrid with install.packages(forecastHybrid) and got these errors

```
Error: package or namespace load failed for ‘forecast’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/lib/R/library/uroot/libs/uroot.so':
  libcudart.so.9.1: cannot open shared object file: No such file or directory
Error : package ‘forecast’ could not be loaded
ERROR: lazy loading failed for package ‘forecastHybrid’
* removing ‘/usr/lib/R/library/forecastHybrid’
```
```
$ locate libcudart
/usr/local/cuda-9.2/doc/man/man7/libcudart.7
/usr/local/cuda-9.2/doc/man/man7/libcudart.so.7
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudart.so.9.2
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudart.so.9.2.148
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudart_static.a

```

I have cuda-9.2 and libcudart.so.9.2 instead of 9.1

OS is Ubuntu 16.04, R version 3.5.1

**Comment by dashaub** [comment]
@beew This doesn't look to be a problem with the "forecastHybrid" package but rather loading its requirement "forecast". And the problem there is actually loading _its_ dependency "uroot".

I haven't done anything with CUDA setup, so I can't help you there. You've problem seen this already, but maybe it helps
https://cran.r-project.org/web/packages/uroot/README

**Comment by beew** [comment]
I see. I thought uroot would be pulled in as a dependency automatically. I have install uroot first and now it works. Thanks.
