### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by dashaub** [ellisp/forecastHybrid#9]
Create Rd files and possibly a vignette.

**Comment by ellisp** [comment]
My preference is to use Roxygen2. It's simple enough to get the hang of and is easier (I think) than managing all these .Rd files manually.  The ./build.R/ script has a line that builds all the .Rd files.

**Comment by dashaub** [comment]
Docs for `hybridModel()` and `forecast.hybridModel()` build now. Once we create our plot methods we'll need to revisit this of course.
