### ISSUE TITLE
Forecast reconciliation

### ISSUE THREAD

**Issue by ASLlohmann** [ellisp/forecastHybrid#91]
First of All thanks a lot for this package. As an forecaster in economic data, it is a very valuable tool in my professional life. 

I am particularly interested by the  `ThiefModel` function.  It would be nice to be able to chose the reconcilation method  because it is an important point in Temporal hierarchies 

I am currently using my a version of your package where I made this possible.  It is was easy.

```thiefModelv2 <- function(y, models = "aefnt", h = 2 * frequency(y), verbose = FALSE,
                         comb=c("struc","mse","ols","sam","shr")
```

Just changing two line of the code 

```
 comb=match.arg(comb)

 fc <- thief(y, h = h, forecastfunction = FCFUN, comb=comb)
```

**Comment by dashaub** [comment]
@ASLlohmann That does sound useful. If you're interested in putting together a pull request, I'd accept the change.

**Comment by dashaub** [comment]
Added here: 75d40038dafc45aed8c9c212674edce227288b68
