### ISSUE TITLE
Computation of residuals

### ISSUE THREAD

**Issue by philturk** [ellisp/forecastHybrid#95]
Hi gentlemen:

Thank you for your package and your efforts here.

You should have look at your residuals from your "hybrid" model. In the vignette (and as I verified with a toy example), the fitted values and the residuals are identical. From your vignette, see:

```
head(fitted(hm1))
head(residuals(hm1))
```

So something is amiss.

Best,

-- Phil

**Comment by dashaub** [comment]
@philturk Thanks for the bug report. Fixed in e14758e0a1409ee30ad85d150df039b79bdbad44.
