### ISSUE TITLE
Error on extractForecasts() from a Hybrid Model with cross validation

### ISSUE THREAD

**Issue by mark0100** [ellisp/forecastHybrid#99]
I get an error when i try to extract the forecasts from a hybrid model with cross validation:

> cvMod <- hybridModel(woolyrnq, models = "ns", weights = "cv.errors", rolling=T, windowSize = 100, cvHorizon = 5, horizonAverage = T, num.cores = 4)
Fitting the nnetar model
Fitting the stlm model
Cross validating the nnetar model
Cross validating the stlm model

> extractForecasts(cvMod, horizon=5)
Error in if (horizon > cv$params$maxHorizon) stop("Cannot extract forecasts with a horizon greater than the model maxHorizon") : 
  argument is of length zero

> traceback()
1: extractForecasts(cvMod, horizon = 5)

How do i get the forecasts that were used during cross validation from this hybrid model?

**Comment by dashaub** [comment]
`extractForecasts()` is for objects of class `cvts` created by `cvts()`. If you're wanting the individual forecasts from each cv step, use `cvts()` to create them, not `hybridModel()`; `hybridModel(weights = "cv.errors")` merely uses cv for selection of the weights to use for the forecasting.
